import type { Metadata } from "next"
import Link from "next/link"

import { config } from "@/lib/config"
import { PageShell } from "@/components/pages/PageShell"
import { Bullets, LegalSection, MailLink, P } from "@/components/pages/Prose"

export const metadata: Metadata = {
  title: "Terms of Service — Briefd",
  description:
    "The terms that govern your use of Briefd — the newsletter summarization service.",
}

const LAST_UPDATED = "June 19, 2026"

export default function TermsPage() {
  return (
    <PageShell
      eyebrow={`Legal / Updated ${LAST_UPDATED}`}
      title={
        <>
          Terms of <span className="silver-text">Service.</span>
        </>
      }
      intro="The plain-language agreement between you and Briefd. Use the service and you agree to these terms."
    >
      <LegalSection index="01" kicker="Agreement" title="Accepting these terms">
        <P>
          These Terms of Service (&ldquo;Terms&rdquo;) govern your use of
          Briefd, the website at {config.site.url}, and the Briefd app. By
          creating an account or using the service you agree to these Terms. If
          you don&apos;t agree, please don&apos;t use Briefd.
        </P>
      </LegalSection>

      <LegalSection index="02" kicker="The service" title="What Briefd does">
        <P>
          Briefd connects to your Gmail with read-only access, reads the
          newsletter senders you choose to watch, and uses AI to turn each issue
          into a short brief delivered to you. That&apos;s the whole product.
        </P>
      </LegalSection>

      <LegalSection
        index="03"
        kicker="Your account"
        title="Eligibility &amp; account"
      >
        <Bullets
          items={[
            "You must be at least 13 years old (or the age of digital consent where you live) to use Briefd.",
            "You're responsible for the activity on your account and for keeping your Google sign-in secure.",
            "You agree to provide accurate information and to use Briefd only with an inbox you own or are authorized to use.",
          ]}
        />
      </LegalSection>

      <LegalSection index="04" kicker="Google" title="Gmail &amp; Google terms">
        <P>
          Briefd&apos;s access to your inbox is read-only and governed by our{" "}
          <Link
            href="/privacy"
            className="font-mono text-foreground underline decoration-foreground/30 underline-offset-4 transition-colors hover:decoration-foreground"
          >
            Privacy Policy
          </Link>{" "}
          and{" "}
          <Link
            href="/gmail-access"
            className="font-mono text-foreground underline decoration-foreground/30 underline-offset-4 transition-colors hover:decoration-foreground"
          >
            Gmail access
          </Link>{" "}
          page. Your use of Gmail also remains subject to Google&apos;s own
          terms. You can revoke Briefd&apos;s access at any time from your
          Google Account.
        </P>
      </LegalSection>

      <LegalSection index="05" kicker="Conduct" title="Acceptable use">
        <Bullets
          items={[
            "Don't use Briefd for any unlawful purpose or to infringe anyone's rights.",
            "Don't attempt to break, overload, reverse-engineer, or gain unauthorized access to the service.",
            "Don't use Briefd to access an inbox you aren't authorized to use.",
          ]}
        />
      </LegalSection>

      <LegalSection index="06" kicker="AI output" title="About the summaries">
        <P>
          Briefs are generated by AI and may occasionally be incomplete or
          inaccurate. They&apos;re a convenience, not a substitute for the
          original newsletter. Always rely on the source for anything important
          — the original is one tap away.
        </P>
      </LegalSection>

      <LegalSection index="07" kicker="Ownership" title="Intellectual property">
        <P>
          The Briefd name, brand, and software are owned by us. The newsletters
          you summarize remain the property of their respective authors and
          publishers; Briefd processes them on your behalf solely to produce
          your personal briefs.
        </P>
      </LegalSection>

      <LegalSection
        index="08"
        kicker="Availability"
        title="Changes &amp; availability"
      >
        <P>
          Briefd is offered on an &ldquo;as available&rdquo; basis and may be in
          active development. We may add, change, or discontinue features, and
          we can&apos;t guarantee uninterrupted service.
        </P>
      </LegalSection>

      <LegalSection
        index="09"
        kicker="Disclaimer"
        title="Warranties &amp; liability"
      >
        <P>
          Briefd is provided &ldquo;as is&rdquo; without warranties of any kind.
          To the maximum extent permitted by law, we are not liable for any
          indirect, incidental, or consequential damages arising from your use
          of the service.
        </P>
      </LegalSection>

      <LegalSection index="10" kicker="Termination" title="Ending your use">
        <P>
          You can stop using Briefd and delete your account at any time. We may
          suspend or terminate access if these Terms are violated. On
          termination, your stored data is deleted as described in the Privacy
          Policy.
        </P>
      </LegalSection>

      <LegalSection index="11" kicker="Governing law" title="Jurisdiction">
        <P>
          These Terms are governed by the laws of India, and any disputes are
          subject to the exclusive jurisdiction of the courts of India.
        </P>
      </LegalSection>

      <LegalSection index="12" kicker="Contact" title="Questions">
        <P>
          Anything unclear? Email <MailLink email={config.site.email} /> and
          we&apos;ll help.
        </P>
      </LegalSection>
    </PageShell>
  )
}
